magento_connector:
    connection:
        base_url: <base_url>
        api_end_point: <api_end_point>
        consumer_key: <consumer_key>
        consumer_secret: <consumer_secret>
        access_token: <access_token>
        access_token_secret: <access_token_secret>
